services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www/html
    networks:
      - project1


  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - project1


  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - "MARIADB_ROOT_PASSWORD=pass123"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - project1


networks:
  project1:

volumes:
  website:
  db_data: